# Generated by Django 3.2.16 on 2022-12-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blogmodel_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='imgage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
