# Generated by Django 3.2.16 on 2022-12-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221226_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='users',
            new_name='user',
        ),
    ]
